# -*- coding: utf-8 -*-
"""Validator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iRO1YcRBJyqwczDNLO9AEoAm3T9Sq8Og
"""

import os
import re
import time
import unicodedata
from dataclasses import dataclass
from urllib.parse import urlparse
from collections import defaultdict, deque
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


class ErrorCode:
    POLICY_MALFORMED = "POLICY_MALFORMED"
    CAPABILITY_NOT_FOUND = "CAPABILITY_NOT_FOUND"
    CAPABILITY_DENIED = "CAPABILITY_DENIED"

    PATH_ESCAPES_WORKSPACE = "PATH_ESCAPES_WORKSPACE"
    PATH_DENIED = "PATH_DENIED"
    PATH_NOT_ALLOWED = "PATH_NOT_ALLOWED"
    PATH_INVALID = "PATH_INVALID"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"

    ENDPOINT_INVALID = "ENDPOINT_INVALID"
    ENDPOINT_DENIED = "ENDPOINT_DENIED"
    ENDPOINT_NOT_ALLOWED = "ENDPOINT_NOT_ALLOWED"

    INJECTION_DETECTED = "INJECTION_DETECTED"
    RATE_LIMITED = "RATE_LIMITED"

    OK = "OK"


@dataclass(frozen=True)
class ValidationResult:
    allowed: bool
    code: str
    message: str
    details: Optional[Dict[str, Any]] = None


def _normalize_text(s: str) -> str:
    """
    Normalize input to reduce bypasses:
    - Unicode normalization (NFKC)
    - casefold
    - collapse whitespace
    """
    s = unicodedata.normalize("NFKC", s)
    s = s.casefold()
    s = re.sub(r"\s+", " ", s).strip()
    return s


def _squash_alpha(s: str) -> str:
    """
    Remove non-letters/digits so spaced-out / punctuated attacks collapse:
    'b y p a s s  s e c u r i t y' -> 'bypasssecurity'
    """
    return re.sub(r"[^a-z0-9]+", "", _normalize_text(s))


def _is_subpath(child: Path, parent: Path) -> bool:
    """
    Returns True if child is within parent after resolving.
    """
    try:
        child_res = child.resolve(strict=False)
        parent_res = parent.resolve(strict=False)
        return parent_res == child_res or parent_res in child_res.parents
    except Exception:
        return False


def _compile_regex_list(patterns: List[str]) -> Tuple[Optional[List[re.Pattern]], Optional[str]]:
    compiled = []
    for p in patterns:
        try:
            compiled.append(re.compile(p))
        except re.error as e:
            return None, f"Invalid regex pattern: {p!r} ({e})"
    return compiled, None


class ToolValidatorV2:
    """
    Capability-gated validator with defense-in-depth.

    Supports:
      - filesystem.read/write constraints (allow/deny, workspace containment, max_file_size)
      - http.request constraints (endpoint allow/deny regex)
      - prompt injection heuristics on string params
      - optional rate limiting per capability (sliding window)
      - structured audit events
    """

    DEFAULT_INJECTION_PHRASES = [
        "ignore previous",
        "disregard instructions",
        "override policy",
        "bypass security",
        "jailbreak",
        "do anything now",
    ]

    def __init__(
        self,
        policy: Dict[str, Any],
        base_workspace: str = "/workspace",
        audit_log: bool = True,
        rate_limit: Optional[Dict[str, Any]] = None,
    ):
        """
        rate_limit example:
          {"max_calls": 30, "window_seconds": 60}   # per capability
        """
        self.policy = policy
        self.base_workspace = Path(base_workspace)
        self.audit_log_enabled = audit_log

        self.rate_limit = rate_limit or None
        self._rate_buckets = defaultdict(lambda: deque())  # capability -> deque[timestamps]

        # Precompile injection patterns
        self._inj_phrases_norm = [_normalize_text(x) for x in self.DEFAULT_INJECTION_PHRASES]
        self._inj_phrases_squash = [_squash_alpha(x) for x in self.DEFAULT_INJECTION_PHRASES]

        # Validate policy early
        ok, msg = self._validate_policy_schema(policy)
        if not ok:
            raise ValueError(f"Policy schema invalid: {msg}")

    # ---------------------------
    # Public API
    # ---------------------------

    def validate(self, capability: str, params: Dict[str, Any]) -> ValidationResult:
        # Rate limit (optional)
        rl = self._check_rate_limit(capability)
        if rl is not None:
            self._audit(False, ErrorCode.RATE_LIMITED, "Rate limited", capability, params, rl)
            return ValidationResult(False, ErrorCode.RATE_LIMITED, "Rate limited.", rl)

        cap_cfg = self._get_capability_config(capability)
        if cap_cfg is None:
            self._audit(False, ErrorCode.CAPABILITY_NOT_FOUND, "Capability not found", capability, params)
            return ValidationResult(False, ErrorCode.CAPABILITY_NOT_FOUND, f"Capability {capability!r} not found.")

        if not cap_cfg.get("allowed", False):
            self._audit(False, ErrorCode.CAPABILITY_DENIED, "Capability denied by policy", capability, params)
            return ValidationResult(False, ErrorCode.CAPABILITY_DENIED, f"Capability {capability!r} is denied by policy.")

        # Injection heuristics on string params
        inj = self._detect_injection(params)
        if inj is not None:
            self._audit(False, ErrorCode.INJECTION_DETECTED, "Injection detected", capability, params, inj)
            return ValidationResult(False, ErrorCode.INJECTION_DETECTED, "Potential injection detected in parameters.", inj)

        constraints = cap_cfg.get("constraints", {}) or {}

        # Dispatch by capability prefix / type
        if capability.startswith("filesystem."):
            return self._validate_filesystem(capability, params, constraints)
        if capability in ("http.request", "http.fetch", "http.get", "http.post"):
            return self._validate_http(capability, params, constraints)

        # Default: allowed if capability is allowed and no other rules exist
        self._audit(True, ErrorCode.OK, "Allowed (no additional constraints)", capability, params)
        return ValidationResult(True, ErrorCode.OK, "Allowed.")

    # ---------------------------
    # Policy + Capability Helpers
    # ---------------------------

    def _validate_policy_schema(self, policy: Dict[str, Any]) -> Tuple[bool, str]:
        if not isinstance(policy, dict):
            return False, "Policy must be a dict."
        caps = policy.get("capabilities")
        if not isinstance(caps, list):
            return False, "Policy.capabilities must be a list."

        for i, c in enumerate(caps):
            if not isinstance(c, dict):
                return False, f"Capability entry {i} must be a dict."
            if "name" not in c or not isinstance(c["name"], str):
                return False, f"Capability entry {i} missing valid 'name' string."
            if "allowed" in c and not isinstance(c["allowed"], bool):
                return False, f"Capability {c['name']!r} has non-bool 'allowed'."
            if "constraints" in c and not isinstance(c["constraints"], dict):
                return False, f"Capability {c['name']!r} has non-dict 'constraints'."

            # Optional: validate constraints types if present
            cons = c.get("constraints", {}) or {}
            if "paths" in cons:
                p = cons["paths"]
                if not isinstance(p, dict):
                    return False, f"Capability {c['name']!r}: constraints.paths must be dict."
                for k in ("allow", "deny"):
                    if k in p and not (isinstance(p[k], list) and all(isinstance(x, str) for x in p[k])):
                        return False, f"Capability {c['name']!r}: constraints.paths.{k} must be list[str]."
            if "endpoints" in cons:
                e = cons["endpoints"]
                if not isinstance(e, dict):
                    return False, f"Capability {c['name']!r}: constraints.endpoints must be dict."
                for k in ("allow", "deny"):
                    if k in e and not (isinstance(e[k], list) and all(isinstance(x, str) for x in e[k])):
                        return False, f"Capability {c['name']!r}: constraints.endpoints.{k} must be list[str]."
            if "max_file_size" in cons and not isinstance(cons["max_file_size"], int):
                return False, f"Capability {c['name']!r}: constraints.max_file_size must be int."
        return True, "OK"

    def _get_capability_config(self, capability: str) -> Optional[Dict[str, Any]]:
        caps = self.policy.get("capabilities", [])
        for c in caps:
            if c.get("name") == capability:
                return c
        return None

    # ---------------------------
    # Injection Detection
    # ---------------------------

    def _detect_injection(self, params: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        hits = []
        for k, v in (params or {}).items():
            if isinstance(v, str):
                n = _normalize_text(v)
                s = _squash_alpha(v)

                for phrase in self._inj_phrases_norm:
                    if phrase in n:
                        hits.append({"field": k, "match": phrase, "mode": "normalized_substring"})
                for phrase in self._inj_phrases_squash:
                    if phrase and phrase in s:
                        hits.append({"field": k, "match": phrase, "mode": "squashed_substring"})

        return {"hits": hits} if hits else None

    # ---------------------------
    # Filesystem Validation
    # ---------------------------

    def _validate_filesystem(self, capability: str, params: Dict[str, Any], constraints: Dict[str, Any]) -> ValidationResult:
        path = params.get("path")
        if not isinstance(path, str) or not path.strip():
            self._audit(False, ErrorCode.PATH_INVALID, "Missing/invalid path", capability, params)
            return ValidationResult(False, ErrorCode.PATH_INVALID, "Missing or invalid 'path' parameter.")

        # Resolve requested path against workspace (treat relative as within workspace)
        req_path = Path(path)

        # If absolute, still enforce it must be within base_workspace
        if req_path.is_absolute():
            resolved = req_path.resolve(strict=False)
        else:
            resolved = (self.base_workspace / req_path).resolve(strict=False)

        if not _is_subpath(resolved, self.base_workspace):
            details = {"resolved": str(resolved), "workspace": str(self.base_workspace)}
            self._audit(False, ErrorCode.PATH_ESCAPES_WORKSPACE, "Path escapes workspace", capability, params, details)
            return ValidationResult(False, ErrorCode.PATH_ESCAPES_WORKSPACE, "Path escapes workspace boundary.", details)

        # Allow/Deny lists (deny wins)
        paths_cfg = (constraints.get("paths") or {})
        deny_list = [Path(p).resolve(strict=False) for p in paths_cfg.get("deny", [])]
        allow_list = [Path(p).resolve(strict=False) for p in paths_cfg.get("allow", [])]

        for d in deny_list:
            if _is_subpath(resolved, d) or resolved == d:
                details = {"resolved": str(resolved), "denied_by": str(d)}
                self._audit(False, ErrorCode.PATH_DENIED, "Path denied by policy", capability, params, details)
                return ValidationResult(False, ErrorCode.PATH_DENIED, "Path explicitly denied by policy.", details)

        if allow_list:
            allowed = any(_is_subpath(resolved, a) or resolved == a for a in allow_list)
            if not allowed:
                details = {"resolved": str(resolved), "allowed_roots": [str(a) for a in allow_list]}
                self._audit(False, ErrorCode.PATH_NOT_ALLOWED, "Path not in allowlist", capability, params, details)
                return ValidationResult(False, ErrorCode.PATH_NOT_ALLOWED, "Path not permitted by allowlist.", details)

        # Max file size check (only if file exists and capability reads it)
        max_sz = constraints.get("max_file_size")
        if isinstance(max_sz, int) and capability in ("filesystem.read", "filesystem.open", "filesystem.get"):
            try:
                if resolved.exists() and resolved.is_file():
                    size = resolved.stat().st_size
                    if size > max_sz:
                        details = {"resolved": str(resolved), "size": size, "max_file_size": max_sz}
                        self._audit(False, ErrorCode.FILE_TOO_LARGE, "File too large", capability, params, details)
                        return ValidationResult(False, ErrorCode.FILE_TOO_LARGE, "File exceeds max_file_size constraint.", details)
            except Exception as e:
                # If you prefer “fail closed” here, flip to deny.
                details = {"resolved": str(resolved), "error": str(e)}
                self._audit(False, ErrorCode.PATH_INVALID, "Could not stat file", capability, params, details)
                return ValidationResult(False, ErrorCode.PATH_INVALID, "Could not validate file metadata.", details)

        self._audit(True, ErrorCode.OK, "Filesystem request allowed", capability, params, {"resolved": str(resolved)})
        return ValidationResult(True, ErrorCode.OK, "Allowed.", {"resolved": str(resolved)})

    # ---------------------------
    # HTTP Validation
    # ---------------------------

    def _validate_http(self, capability: str, params: Dict[str, Any], constraints: Dict[str, Any]) -> ValidationResult:
        url = params.get("url") or params.get("endpoint")
        if not isinstance(url, str) or not url.strip():
            self._audit(False, ErrorCode.ENDPOINT_INVALID, "Missing/invalid url", capability, params)
            return ValidationResult(False, ErrorCode.ENDPOINT_INVALID, "Missing or invalid 'url'/'endpoint' parameter.")

        url_norm = url.strip()
        parsed = urlparse(url_norm)

        # Basic sanity: require scheme+netloc for http(s)
        if parsed.scheme not in ("http", "https") or not parsed.netloc:
            details = {"url": url_norm}
            self._audit(False, ErrorCode.ENDPOINT_INVALID, "URL parse invalid", capability, params, details)
            return ValidationResult(False, ErrorCode.ENDPOINT_INVALID, "URL must be absolute http(s) with host.", details)

        endpoints_cfg = (constraints.get("endpoints") or {})
        deny_patterns, err = _compile_regex_list(endpoints_cfg.get("deny", []))
        if err:
            return ValidationResult(False, ErrorCode.POLICY_MALFORMED, err)

        allow_patterns, err = _compile_regex_list(endpoints_cfg.get("allow", []))
        if err:
            return ValidationResult(False, ErrorCode.POLICY_MALFORMED, err)

        # Deny wins
        if deny_patterns and any(p.search(url_norm) for p in deny_patterns):
            details = {"url": url_norm}
            self._audit(False, ErrorCode.ENDPOINT_DENIED, "Endpoint denied by policy", capability, params, details)
            return ValidationResult(False, ErrorCode.ENDPOINT_DENIED, "Endpoint explicitly denied by policy.", details)

        if allow_patterns:
            if not any(p.search(url_norm) for p in allow_patterns):
                details = {"url": url_norm}
                self._audit(False, ErrorCode.ENDPOINT_NOT_ALLOWED, "Endpoint not in allowlist", capability, params, details)
                return ValidationResult(False, ErrorCode.ENDPOINT_NOT_ALLOWED, "Endpoint not permitted by allowlist.", details)

        self._audit(True, ErrorCode.OK, "HTTP request allowed", capability, params, {"url": url_norm})
        return ValidationResult(True, ErrorCode.OK, "Allowed.", {"url": url_norm})

    # ---------------------------
    # Rate Limiting
    # ---------------------------

    def _check_rate_limit(self, capability: str) -> Optional[Dict[str, Any]]:
        if not self.rate_limit:
            return None

        max_calls = int(self.rate_limit.get("max_calls", 0))
        window = int(self.rate_limit.get("window_seconds", 0))
        if max_calls <= 0 or window <= 0:
            return None

        now = time.time()
        q = self._rate_buckets[capability]

        # purge old
        while q and (now - q[0]) > window:
            q.popleft()

        if len(q) >= max_calls:
            return {"capability": capability, "max_calls": max_calls, "window_seconds": window}

        q.append(now)
        return None

    # ---------------------------
    # Audit
    # ---------------------------

    def _audit(
        self,
        allowed: bool,
        code: str,
        message: str,
        capability: str,
        params: Dict[str, Any],
        details: Optional[Dict[str, Any]] = None,
    ):
        if not self.audit_log_enabled:
            return

        event = {
            "ts": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "allowed": allowed,
            "code": code,
            "message": message,
            "capability": capability,
            "params_keys": list((params or {}).keys()),
            "details": details or {},
        }
        # Replace with your real AuditLogger integration:
        print("[AUDIT]", event)

policy = {
    "capabilities": [
        {
            "name": "filesystem.read",
            "allowed": True,
            "constraints": {
                "paths": {"allow": ["/workspace/src"], "deny": ["/workspace/src/private.py"]},
                "max_file_size": 1024,
            },
        },
        {
            "name": "http.request",
            "allowed": True,
            "constraints": {
                "endpoints": {
                    "allow": [r"^https://api\.mycompany\.com/.*$"],
                    "deny": [r".*/admin/.*"],
                }
            },
        },
    ]
}

v = ToolValidatorV2(policy, base_workspace="/workspace", audit_log=True, rate_limit={"max_calls": 5, "window_seconds": 10})

print(v.validate("filesystem.read", {"path": "../../etc/passwd"}))              # should BLOCK (workspace escape)
print(v.validate("filesystem.read", {"path": "src/private.py"}))               # should BLOCK (deny)
print(v.validate("filesystem.read", {"path": "src/somefile.py"}))              # allow if within allowlist
print(v.validate("http.request", {"url": "https://api.mycompany.com/v1/x"}))   # allow
print(v.validate("http.request", {"url": "https://api.mycompany.com/admin/x"})) # BLOCK (deny)
print(v.validate("http.request", {"url": "https://evil.com/x"}))              # BLOCK (not allowed)

# Injection bypass attempt (spaced + unicode normalized)
print(v.validate("filesystem.read", {"path": "src/readme.md", "note": "b y p a s s   s e c u r i t y"}))  # BLOCK